version: '3.8'

services:
  # Backend Rust (TESS-MCP)
  rust-backend:
    build:
      context: ../mcp-server-agno-xtp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MCP_API_KEY=${MCP_API_KEY:-demo-key}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Frontend Python (MCP SDK)
  python-frontend:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - RUST_BACKEND_URL=http://rust-backend:3000
      - MCP_API_KEY=${MCP_API_KEY:-demo-key}
    depends_on:
      - rust-backend
    restart: unless-stopped 